// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrBillSplit.Backend.Data;

#nullable disable

namespace QrBillSplit.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717064823_AddAmountPaidToBillItem")]
    partial class AddAmountPaidToBillItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QrBillSplit.Backend.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("LockedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaidByUserId")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("TableSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TableSessionId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("QrBillSplit.Backend.Models.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TableSessionId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("QrBillSplit.Backend.Models.TableSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TableSessions");
                });

            modelBuilder.Entity("QrBillSplit.Backend.Models.BillItem", b =>
                {
                    b.HasOne("QrBillSplit.Backend.Models.TableSession", "TableSession")
                        .WithMany("BillItems")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("QrBillSplit.Backend.Models.Participant", b =>
                {
                    b.HasOne("QrBillSplit.Backend.Models.TableSession", "TableSession")
                        .WithMany("Participants")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("QrBillSplit.Backend.Models.TableSession", b =>
                {
                    b.Navigation("BillItems");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
